ALTER TABLE `bookings`
  MODIFY `status` ENUM('PENDING_CONFIRMATION','PENDING','CONFIRMED','PLAYED','CANCELLED','NO_SHOW','BLOCKED') NOT NULL DEFAULT 'CONFIRMED';

UPDATE `bookings`
SET `status` = 'PENDING'
WHERE `status` = 'PENDING_CONFIRMATION';

ALTER TABLE `bookings`
  MODIFY `status` ENUM('PENDING','CONFIRMED','PLAYED','CANCELLED','NO_SHOW','BLOCKED') NOT NULL DEFAULT 'CONFIRMED';