UPDATE bookings SET status = 'CONFIRMED' WHERE status = 'RESERVED';

ALTER TABLE bookings
MODIFY COLUMN status ENUM('CONFIRMED', 'PLAYED', 'CANCELLED', 'NO_SHOW', 'BLOCKED')
NOT NULL DEFAULT 'CONFIRMED';
