ALTER TABLE `users`
  ADD COLUMN `status` ENUM('PENDING_VERIFICATION', 'VERIFIED') NOT NULL DEFAULT 'PENDING_VERIFICATION';

UPDATE `users`
SET `status` = 'VERIFIED'
WHERE `phoneVerified` = true OR `role` IN ('ADMIN', 'SUPERADMIN');